DROP TABLE IF EXISTS Hikes;

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE Hikes (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    track GEOGRAPHY(LINESTRINGZ, 4326),
    simplified_profile JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);