# config.yaml
spec:
  template:
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/trailhead-mvp/trailhead-repo/cms:latest
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_CLIENT
          value: "postgres"
        - name: DATABASE_HOST
          value: "/cloudsql/trailhead-mvp:europe-west2:hiking-project-db-233ae46e"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "hikes_db"
        - name: DATABASE_USERNAME
          value: "hike_admin"
        - name: DATABASE_PASSWORD
          value: ""rLU~cv0BLg`|Ob{"
        - name: DATABASE_SSL
          value: "true"
        - name: APP_KEYS
          value: "someRandomKey1,someOtherRandomKey2"